### PR TITLE
Add support for offsetX and offsetY in MouseEvent

### PR DESCRIPTION
**Pull request by singpolyma**

### CODE REVIEW

**Comment by JordanMartinez** [comment]
You might want to see #2...

**Comment by singpolyma** [comment]
@JordanMartinez these days it seems it is standardized: https://web.archive.org/web/20200919224107/https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface

**Comment by hdgarrood** [comment]
Since it's part of the CSSOM spec I think the best place for these is probably the web-cssom library.

**Comment by singpolyma** [comment]
@hdgarrood could do that... how should that look, just a module with the same name as here but under the CSSOM hierarchy that exports the offset functions?

**Comment by hdgarrood** [comment]
I'm not certain since I don't actually have too much involvement in the maintenance of these libraries, but yeah, I think `Web.CSSOM.MouseEvent` sounds reasonable.

**Comment by singpolyma** [comment]
Ok, alternate now here: https://github.com/purescript-web/purescript-web-cssom/pull/5

**Comment by thomashoneyman** [comment]
I've approved https://github.com/purescript-web/purescript-web-cssom/pull/5, so this can be closed.

**Pull request closed without merging**
